# Generated by Django 5.0.4 on 2024-04-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='availability',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('pclaptops', 'PC/Laptop'), ('vrheadset', 'VR Headset'), ('camsensor', 'Camera/Sensors'), ('pcperipheral', 'PC Peripherals'), ('furniture', 'Furniture'), ('tripod', 'Tripod'), ('powercable', 'Power/Cable'), ('vrcontroller', 'VR Controller'), ('other', 'Other')], max_length=50),
        ),
    ]
