# Generated by Django 5.0.4 on 2024-04-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_rename_availability_equipment_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
