# Generated by Django 5.0.4 on 2024-04-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_alter_equipment_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='return_date',
            new_name='audit',
        ),
    ]
