# Generated by Django 5.0.4 on 2024-04-26 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_rename_return_date_equipment_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(choices=[('XRLabBlueCabinet', 'XRLab Blue Cabinet'), ('XRLab', 'XRLab'), ('XRLabBlueCabinetLarge', 'XRLab Blue Cabinet Large'), ('XRLabMediumWoodenCabinet', 'XRLab Medium Wooden Cabinet'), ('other', 'Other')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
