# Generated by Django 5.0.4 on 2024-04-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0008_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
